// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/cns/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterChainNameRequest struct {
	ChainName          string       `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	Owner              string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Seed               []string     `protobuf:"bytes,3,rep,name=seed,proto3" json:"seed,omitempty"`
	SourceCodeUrl      string       `protobuf:"bytes,4,opt,name=source_code_url,json=sourceCodeUrl,proto3" json:"source_code_url,omitempty"`
	CanonicalIbcClient string       `protobuf:"bytes,5,opt,name=canonical_ibc_client,json=canonicalIbcClient,proto3" json:"canonical_ibc_client,omitempty"`
	Version            *VersionInfo `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *MsgRegisterChainNameRequest) Reset()         { *m = MsgRegisterChainNameRequest{} }
func (m *MsgRegisterChainNameRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterChainNameRequest) ProtoMessage()    {}
func (*MsgRegisterChainNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c582da2b0732e9, []int{0}
}
func (m *MsgRegisterChainNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterChainNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterChainNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterChainNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterChainNameRequest.Merge(m, src)
}
func (m *MsgRegisterChainNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterChainNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterChainNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterChainNameRequest proto.InternalMessageInfo

func (m *MsgRegisterChainNameRequest) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *MsgRegisterChainNameRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgRegisterChainNameRequest) GetSeed() []string {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *MsgRegisterChainNameRequest) GetSourceCodeUrl() string {
	if m != nil {
		return m.SourceCodeUrl
	}
	return ""
}

func (m *MsgRegisterChainNameRequest) GetCanonicalIbcClient() string {
	if m != nil {
		return m.CanonicalIbcClient
	}
	return ""
}

func (m *MsgRegisterChainNameRequest) GetVersion() *VersionInfo {
	if m != nil {
		return m.Version
	}
	return nil
}

type MsgRegisterChainNameResponse struct {
}

func (m *MsgRegisterChainNameResponse) Reset()         { *m = MsgRegisterChainNameResponse{} }
func (m *MsgRegisterChainNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterChainNameResponse) ProtoMessage()    {}
func (*MsgRegisterChainNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c582da2b0732e9, []int{1}
}
func (m *MsgRegisterChainNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterChainNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterChainNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterChainNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterChainNameResponse.Merge(m, src)
}
func (m *MsgRegisterChainNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterChainNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterChainNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterChainNameResponse proto.InternalMessageInfo

type MsgUpdateChainInfoRequest struct {
	ChainName          string       `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	Owner              string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Seed               []string     `protobuf:"bytes,3,rep,name=seed,proto3" json:"seed,omitempty"`
	SourceCodeUrl      string       `protobuf:"bytes,4,opt,name=source_code_url,json=sourceCodeUrl,proto3" json:"source_code_url,omitempty"`
	CanonicalIbcClient string       `protobuf:"bytes,5,opt,name=canonical_ibc_client,json=canonicalIbcClient,proto3" json:"canonical_ibc_client,omitempty"`
	Version            *VersionInfo `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *MsgUpdateChainInfoRequest) Reset()         { *m = MsgUpdateChainInfoRequest{} }
func (m *MsgUpdateChainInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChainInfoRequest) ProtoMessage()    {}
func (*MsgUpdateChainInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c582da2b0732e9, []int{2}
}
func (m *MsgUpdateChainInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChainInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChainInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChainInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChainInfoRequest.Merge(m, src)
}
func (m *MsgUpdateChainInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChainInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChainInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChainInfoRequest proto.InternalMessageInfo

func (m *MsgUpdateChainInfoRequest) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *MsgUpdateChainInfoRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUpdateChainInfoRequest) GetSeed() []string {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *MsgUpdateChainInfoRequest) GetSourceCodeUrl() string {
	if m != nil {
		return m.SourceCodeUrl
	}
	return ""
}

func (m *MsgUpdateChainInfoRequest) GetCanonicalIbcClient() string {
	if m != nil {
		return m.CanonicalIbcClient
	}
	return ""
}

func (m *MsgUpdateChainInfoRequest) GetVersion() *VersionInfo {
	if m != nil {
		return m.Version
	}
	return nil
}

type MsgUpdateChainInfoResponse struct {
}

func (m *MsgUpdateChainInfoResponse) Reset()         { *m = MsgUpdateChainInfoResponse{} }
func (m *MsgUpdateChainInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChainInfoResponse) ProtoMessage()    {}
func (*MsgUpdateChainInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c582da2b0732e9, []int{3}
}
func (m *MsgUpdateChainInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChainInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChainInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChainInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChainInfoResponse.Merge(m, src)
}
func (m *MsgUpdateChainInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChainInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChainInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChainInfoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterChainNameRequest)(nil), "tendermint.cns.cns.MsgRegisterChainNameRequest")
	proto.RegisterType((*MsgRegisterChainNameResponse)(nil), "tendermint.cns.cns.MsgRegisterChainNameResponse")
	proto.RegisterType((*MsgUpdateChainInfoRequest)(nil), "tendermint.cns.cns.MsgUpdateChainInfoRequest")
	proto.RegisterType((*MsgUpdateChainInfoResponse)(nil), "tendermint.cns.cns.MsgUpdateChainInfoResponse")
}

func init() { proto.RegisterFile("proto/cns/tx.proto", fileDescriptor_c2c582da2b0732e9) }

var fileDescriptor_c2c582da2b0732e9 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x93, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0x6b, 0xfa, 0x07, 0xd5, 0x08, 0x55, 0x98, 0x0e, 0x21, 0x94, 0x50, 0x55, 0x02, 0x75,
	0x21, 0xa9, 0xca, 0xc4, 0x84, 0x44, 0xa7, 0x0e, 0x65, 0x88, 0x54, 0x06, 0x96, 0x28, 0x71, 0x0e,
	0xa9, 0xa5, 0xc4, 0x0e, 0xb6, 0x53, 0xca, 0x5b, 0xf0, 0x58, 0x8c, 0x1d, 0x19, 0x51, 0xfb, 0x00,
	0xcc, 0x88, 0x05, 0xc5, 0x56, 0xa9, 0x44, 0x73, 0xaf, 0xba, 0xdf, 0x21, 0x92, 0x8f, 0xbf, 0xdf,
	0xe7, 0x13, 0x7f, 0xc9, 0xc1, 0xa4, 0x94, 0x42, 0x8b, 0x80, 0x72, 0x15, 0xe8, 0x9d, 0x6f, 0x0a,
	0x42, 0x34, 0xf0, 0x14, 0x64, 0xc1, 0xb8, 0xf6, 0x29, 0x57, 0xf5, 0xe3, 0x0e, 0x33, 0x91, 0x09,
	0xcb, 0xd6, 0x2b, 0x4b, 0xba, 0x8f, 0xcf, 0xee, 0x1a, 0x34, 0xd5, 0xe4, 0x0f, 0xc2, 0x4f, 0x57,
	0x2a, 0x0b, 0x21, 0x63, 0x4a, 0x83, 0x5c, 0x6c, 0x62, 0xc6, 0xdf, 0xc7, 0x05, 0x84, 0xf0, 0xb9,
	0x02, 0xa5, 0xc9, 0x33, 0x8c, 0x69, 0xbd, 0x17, 0xf1, 0xb8, 0x00, 0x07, 0x8d, 0xd1, 0xb4, 0x1f,
	0xf6, 0xe9, 0x89, 0x22, 0x43, 0xdc, 0x15, 0x5f, 0x38, 0x48, 0xe7, 0x9e, 0x51, 0x6c, 0x41, 0x08,
	0xee, 0x28, 0x80, 0xd4, 0x69, 0x8f, 0xdb, 0xd3, 0x7e, 0x68, 0xd6, 0xe4, 0x25, 0x1e, 0x28, 0x51,
	0x49, 0x0a, 0x11, 0x15, 0x29, 0x44, 0x95, 0xcc, 0x9d, 0x8e, 0xf1, 0x3c, 0xb4, 0xdb, 0x0b, 0x91,
	0xc2, 0x5a, 0xe6, 0x64, 0x86, 0x87, 0x34, 0xe6, 0x82, 0x33, 0x1a, 0xe7, 0x11, 0x4b, 0x68, 0x44,
	0x73, 0x06, 0x5c, 0x3b, 0x5d, 0x03, 0x93, 0x7f, 0xda, 0x32, 0xa1, 0x0b, 0xa3, 0x90, 0x37, 0xf8,
	0xfe, 0x16, 0xa4, 0x62, 0x82, 0x3b, 0xbd, 0x31, 0x9a, 0x3e, 0x98, 0x3f, 0xf7, 0x2f, 0x33, 0xf1,
	0x3f, 0x58, 0x64, 0xc9, 0x3f, 0x89, 0xf0, 0xc4, 0x4f, 0x3c, 0x3c, 0x6a, 0xbe, 0xbc, 0x2a, 0x05,
	0x57, 0x30, 0xf9, 0x8d, 0xf0, 0x93, 0x95, 0xca, 0xd6, 0x65, 0x1a, 0x6b, 0x30, 0xb2, 0xf1, 0xdf,
	0x89, 0x6c, 0x46, 0xd8, 0x6d, 0xba, 0xba, 0x4d, 0x66, 0xfe, 0x0b, 0xe1, 0xf6, 0x4a, 0x65, 0x64,
	0x8b, 0x1f, 0x5d, 0xc4, 0x47, 0x82, 0xa6, 0x26, 0xb7, 0xfc, 0x65, 0xee, 0xec, 0x7a, 0x83, 0xed,
	0x4f, 0x4a, 0x3c, 0xf8, 0xef, 0xd5, 0xc8, 0xab, 0x1b, 0x0e, 0x69, 0xfe, 0x7a, 0xae, 0x7f, 0x2d,
	0x6e, 0x3b, 0xbe, 0x7b, 0xfb, 0xfd, 0xe0, 0xa1, 0xfd, 0xc1, 0x43, 0x3f, 0x0f, 0x1e, 0xfa, 0x76,
	0xf4, 0x5a, 0xfb, 0xa3, 0xd7, 0xfa, 0x71, 0xf4, 0x5a, 0x1f, 0x5f, 0x64, 0x4c, 0x6f, 0xaa, 0xc4,
	0xa7, 0xa2, 0x08, 0xce, 0x67, 0x9a, 0x41, 0xdb, 0xd9, 0x61, 0xfd, 0x5a, 0x82, 0x4a, 0x7a, 0x66,
	0xe2, 0x5e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x8f, 0xcb, 0x64, 0xc6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterChainName(ctx context.Context, in *MsgRegisterChainNameRequest, opts ...grpc.CallOption) (*MsgRegisterChainNameResponse, error)
	UpdateChainInfo(ctx context.Context, in *MsgUpdateChainInfoRequest, opts ...grpc.CallOption) (*MsgUpdateChainInfoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterChainName(ctx context.Context, in *MsgRegisterChainNameRequest, opts ...grpc.CallOption) (*MsgRegisterChainNameResponse, error) {
	out := new(MsgRegisterChainNameResponse)
	err := c.cc.Invoke(ctx, "/tendermint.cns.cns.Msg/RegisterChainName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateChainInfo(ctx context.Context, in *MsgUpdateChainInfoRequest, opts ...grpc.CallOption) (*MsgUpdateChainInfoResponse, error) {
	out := new(MsgUpdateChainInfoResponse)
	err := c.cc.Invoke(ctx, "/tendermint.cns.cns.Msg/UpdateChainInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterChainName(context.Context, *MsgRegisterChainNameRequest) (*MsgRegisterChainNameResponse, error)
	UpdateChainInfo(context.Context, *MsgUpdateChainInfoRequest) (*MsgUpdateChainInfoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterChainName(ctx context.Context, req *MsgRegisterChainNameRequest) (*MsgRegisterChainNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChainName not implemented")
}
func (*UnimplementedMsgServer) UpdateChainInfo(ctx context.Context, req *MsgUpdateChainInfoRequest) (*MsgUpdateChainInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChainInfo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterChainName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterChainNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterChainName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.cns.cns.Msg/RegisterChainName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterChainName(ctx, req.(*MsgRegisterChainNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateChainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateChainInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateChainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.cns.cns.Msg/UpdateChainInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateChainInfo(ctx, req.(*MsgUpdateChainInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.cns.cns.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChainName",
			Handler:    _Msg_RegisterChainName_Handler,
		},
		{
			MethodName: "UpdateChainInfo",
			Handler:    _Msg_UpdateChainInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cns/tx.proto",
}

func (m *MsgRegisterChainNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterChainNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterChainNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != nil {
		{
			size, err := m.Version.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.CanonicalIbcClient) > 0 {
		i -= len(m.CanonicalIbcClient)
		copy(dAtA[i:], m.CanonicalIbcClient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CanonicalIbcClient)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceCodeUrl) > 0 {
		i -= len(m.SourceCodeUrl)
		copy(dAtA[i:], m.SourceCodeUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceCodeUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Seed) > 0 {
		for iNdEx := len(m.Seed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Seed[iNdEx])
			copy(dAtA[i:], m.Seed[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Seed[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterChainNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterChainNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterChainNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChainInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChainInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChainInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != nil {
		{
			size, err := m.Version.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.CanonicalIbcClient) > 0 {
		i -= len(m.CanonicalIbcClient)
		copy(dAtA[i:], m.CanonicalIbcClient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CanonicalIbcClient)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceCodeUrl) > 0 {
		i -= len(m.SourceCodeUrl)
		copy(dAtA[i:], m.SourceCodeUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceCodeUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Seed) > 0 {
		for iNdEx := len(m.Seed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Seed[iNdEx])
			copy(dAtA[i:], m.Seed[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Seed[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChainInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChainInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChainInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterChainNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Seed) > 0 {
		for _, s := range m.Seed {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.SourceCodeUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CanonicalIbcClient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Version != nil {
		l = m.Version.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterChainNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateChainInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Seed) > 0 {
		for _, s := range m.Seed {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.SourceCodeUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CanonicalIbcClient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Version != nil {
		l = m.Version.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateChainInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterChainNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterChainNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterChainNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = append(m.Seed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceCodeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceCodeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanonicalIbcClient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CanonicalIbcClient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Version == nil {
				m.Version = &VersionInfo{}
			}
			if err := m.Version.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterChainNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterChainNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterChainNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChainInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChainInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChainInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = append(m.Seed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceCodeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceCodeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanonicalIbcClient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CanonicalIbcClient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Version == nil {
				m.Version = &VersionInfo{}
			}
			if err := m.Version.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChainInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChainInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChainInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
